# Generated by Django 3.0.2 on 2020-02-27 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_auto_20200227_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='workers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
