# Generated by Django 3.0.2 on 2020-03-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200227_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='workersInDay',
            field=models.IntegerField(null=True, verbose_name='Number of workers in day'),
        ),
    ]
