# Generated by Django 3.0.2 on 2020-03-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_worktime_workersinday'),
    ]

    operations = [
        migrations.CreateModel(
            name='commenting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000, verbose_name='Comment about ')),
            ],
        ),
        migrations.CreateModel(
            name='grading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0, verbose_name='Grade between 1 and 5')),
                ('choice_text', models.CharField(max_length=2)),
            ],
        ),
    ]
