# Generated by Django 3.0.2 on 2020-03-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_commenting_grading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grading',
            name='choice_text',
            field=models.CharField(max_length=2, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='grading',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Amount received for this rate'),
        ),
    ]
