# Generated by Django 3.0.2 on 2020-03-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('events', '0015_workersinrota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workersinrota',
            name='workers',
            field=models.ManyToManyField(null=True, related_name='workers', to='auth.Group'),
        ),
    ]
